# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 16:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlanSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plan', to='travelplan.RoutePlan')),
            ],
        ),
        migrations.CreateModel(
            name='TourismSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('prefecture', models.CharField(max_length=9)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=12, null=True)),
                ('parkinglot', models.IntegerField(blank=True, null=True)),
                ('holiday', models.CharField(blank=True, max_length=7, null=True)),
                ('business_hours', models.CharField(blank=True, max_length=11, null=True)),
                ('charge', models.PositiveIntegerField(blank=True, null=True)),
                ('coordinate_latitude', models.FloatField(blank=True, null=True)),
                ('coordinate_longitude', models.FloatField(blank=True, null=True)),
                ('grade', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('man', '男性'), ('woman', '女性'), ('unknown', 'その他')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('user_entry_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='routeplanspot',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='travelplan.TourismSpot'),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='travelplan.User'),
        ),
    ]
